// Presets contain scene settings only. Device and appearance settings are kept
// by loadScene; old IDs remain stable for the desktop/bar integration.
export const sceneCatalog = [
  {id:'warm',name:'Quiet evening',tags:['relax','warm'],description:'Steady amber for winding down.',config:{color:'#efb575',brightness:100,effect:'static'}},
  {id:'focus',name:'Clear focus',tags:['focus','work'],description:'A bright, steady warm white.',config:{color:'#f3e5c5',brightness:170,effect:'static'}},
  {id:'ocean',name:'Ocean drift',tags:['relax','ocean'],description:'Slow blue waves around the display.',config:{color:'#79addc',brightness:135,effect:'wave',speed:2}},
  {id:'ember',name:'Slow embers',tags:['relax','warm'],description:'A low, gently flickering fire.',config:{color:'#e79090',brightness:95,effect:'fire',speed:2}},
  {id:'arcade',name:'Arcade chase',tags:['gaming','neon'],description:'A bright neon comet follows your music.',config:{mode:'audio',audioMode:'comet',audioPalette:'neon',audioSpeed:6,audioWidth:35}},
  {id:'duet',name:'Aurora duet',tags:['music','relax'],description:'Mirrored bands in green, blue and violet.',config:{mode:'audio',audioMode:'twin_bounce',audioPalette:'aurora',audioSpeed:3,audioWidth:30}},
  {id:'ripples',name:'Ocean ripples',tags:['music','ocean'],description:'Cool rings spread out from the center.',config:{mode:'audio',audioMode:'ripple',audioPalette:'ocean',audioSpeed:3,audioWidth:20}},
  {id:'bars',name:'Sunset meters',tags:['music','warm'],description:'Orange and rose bars follow the volume.',config:{mode:'audio',audioMode:'vu',audioPalette:'sunset',audioSpeed:4,audioWidth:24}},
  {id:'ribbon',name:'Candy ribbons',tags:['music','pastel'],description:'Wide, slow ribbons in pink and blue.',config:{mode:'audio',audioMode:'wave',audioPalette:'candy',audioSpeed:2,audioWidth:40}},
  {id:'forest',name:'Forest bounce',tags:['music','nature'],description:'A green band moves with the sound.',config:{mode:'audio',audioMode:'bounce',audioPalette:'forest',audioSpeed:4,audioWidth:24}},
  {id:'screen-balanced',name:'Screen · Balanced',tags:['work','everyday'],description:'An everyday balance of detail, response and capture cost.',config:{mode:'screen',fps:15,smoothing:35,depth:60,brightness:119,captureScale:.35}},
  {id:'screen-gaming',name:'Screen · Gaming',tags:['gaming','fast'],description:'A smaller capture for quicker responses and shallow edge sampling.',config:{mode:'screen',fps:30,smoothing:15,depth:24,brightness:150,captureScale:.2}},
  {id:'screen-cinema',name:'Screen · Cinema',tags:['cinema','relax'],description:'Gentle transitions and wider sampled edges for films.',config:{mode:'screen',fps:12,smoothing:75,depth:120,brightness:100,captureScale:.5}},
  {id:'screen-efficient',name:'Screen · Low CPU',tags:['efficient','work'],description:'Fewer, smaller captures for a quiet desktop.',config:{mode:'screen',fps:8,smoothing:50,depth:32,brightness:90,captureScale:.2}},
  {id:'lavender-breathe',name:'Lavender breathing',tags:['relax','pastel'],description:'A slow lavender fade.',config:{color:'#ab94d2',effect:'breathe',brightness:95,speed:2}},
  {id:'reading',name:'Reading lamp',tags:['focus','reading'],description:'Steady warm white for a brighter desk.',config:{color:'#f3e5c5',effect:'static',brightness:150}},
  {id:'night-desk',name:'Night desk',tags:['night','relax'],description:'Dim steady amber.',config:{color:'#efb575',effect:'static',brightness:28}},
  {id:'mint-wave',name:'Mint waves',tags:['relax','nature'],description:'Soft green waves along the strip.',config:{color:'#92c5b4',effect:'wave',brightness:100,speed:3}},
  {id:'prism',name:'Prism trail',tags:['gaming','rainbow'],description:'A quicker rainbow animation.',config:{effect:'rainbow',brightness:140,speed:6}},
  {id:'rose-heartbeat',name:'Rose heartbeat',tags:['relax','rose'],description:'A slow double pulse in rose.',config:{color:'#e79090',effect:'heartbeat',brightness:85,speed:2}},
  {id:'ember-beats',name:'Ember beats',tags:['music','warm'],description:'Warm colors expand from the center with audio.',config:{mode:'audio',audioMode:'beat',audioPalette:'ember',audioSpeed:3,brightness:110}},
  {id:'neon-spectrum',name:'Neon frequencies',tags:['gaming','music'],description:'Neon colors follow frequency energy.',config:{mode:'audio',audioMode:'spectrum',audioPalette:'neon',sensitivity:1.5,brightness:130}},
  {id:'aurora-silk',name:'Northern lights',tags:['relax','aurora'],description:'Layered green and violet curtains flow gently.',config:{effect:'aurora',brightness:105,speed:2}},
  {id:'ocean-depth',name:'Deep ocean',tags:['relax','ocean'],description:'Blue and turquoise currents with overlapping waves.',config:{effect:'ocean',brightness:100,speed:2}},
  {id:'prism-gradient',name:'Prism gradient',tags:['creative','rainbow'],description:'A continuous, slowly moving color blend.',config:{effect:'gradient',color:'#ab94d2',brightness:125,speed:3}},
  {id:'marquee',name:'Neon marquee',tags:['gaming','neon'],description:'Small groups of lights march along the strip.',config:{effect:'theater_chase',color:'#e85ca8',brightness:125,speed:5}},
  {id:'amber-wipe',name:'Amber sweep',tags:['warm','relax'],description:'Warm color progressively fills and clears the strip.',config:{effect:'color_wipe',color:'#efb575',brightness:100,speed:2}},
  {id:'scanner-blue',name:'Blue scanner',tags:['gaming','blue'],description:'A narrow blue beam sweeps back and forth.',config:{effect:'scanner',color:'#79addc',brightness:135,speed:5}},
  {id:'stardust-meteor',name:'Stardust',tags:['night','relax'],description:'A lavender meteor leaves a fading trail.',config:{effect:'meteor',color:'#ab94d2',brightness:110,speed:3}},
  {id:'twinkle-night',name:'Night sky',tags:['night','relax'],description:'Independent stars brighten and fade softly.',config:{effect:'twinkle',color:'#bfd3ff',brightness:85,speed:2}},
  {id:'celebration',name:'Color blossoms',tags:['celebration','creative'],description:'Colorful bursts spread along the strip.',config:{effect:'fireworks',brightness:130,speed:4}},
  {id:'rainbow-ribbons',name:'Rainbow ribbons',tags:['rainbow','creative'],description:'Rainbow color and brightness waves move together.',config:{effect:'rainbow_wave',brightness:135,speed:3}},
  {id:'golden-hour',name:'Golden hour',tags:['warm','relax'],description:'A steady golden glow for the evening.',config:{effect:'static',color:'#ffc477',brightness:115}},
  {id:'moonlight',name:'Moonlight',tags:['night','blue'],description:'Dim, cool white for a quiet room.',config:{effect:'static',color:'#bdcfff',brightness:40}},
  {id:'soft-rose',name:'Soft rose',tags:['pastel','relax'],description:'A still blush of pink.',config:{effect:'static',color:'#edb1bf',brightness:80}},
  {id:'daylight',name:'Daylight desk',tags:['focus','work'],description:'Neutral white for an active workspace.',config:{effect:'static',color:'#f1f4ff',brightness:180}},
  {id:'red-night',name:'Low red',tags:['night','quiet'],description:'A very dim red glow.',config:{effect:'static',color:'#ff4538',brightness:22}},
  {id:'teal-focus',name:'Teal focus',tags:['focus','work'],description:'Steady cool teal with moderate brightness.',config:{effect:'static',color:'#58c6bf',brightness:115}},
  {id:'amber-pulse',name:'Amber pulse',tags:['warm','relax'],description:'A smooth, slow pulse in amber.',config:{effect:'pulse',color:'#efb575',brightness:90,speed:2}},
  {id:'lilac-chase',name:'Lilac trail',tags:['pastel','creative'],description:'A lavender trail travels around the screen.',config:{effect:'chase',color:'#c49dea',brightness:105,speed:3}},
  {id:'mint-bounce',name:'Mint bounce',tags:['nature','creative'],description:'A soft mint trail bounces between the corners.',config:{effect:'chase_bounce',color:'#92c5b4',brightness:110,speed:4}},
  {id:'starry-sparkle',name:'Golden sparks',tags:['celebration','warm'],description:'Small amber lights shimmer across the strip.',config:{effect:'sparkle',color:'#ffca8c',brightness:100,speed:3}},
  {id:'candlelight',name:'Candlelight',tags:['relax','warm'],description:'Slow firelight at a lower brightness.',config:{effect:'fire',brightness:55,speed:1}},
  {id:'rainbow-drift',name:'Rainbow drift',tags:['rainbow','relax'],description:'An unhurried, softly lit rainbow.',config:{effect:'rainbow',brightness:85,speed:1}},
  {id:'aurora-spectrum',name:'Aurora frequencies',tags:['music','aurora'],description:'Green and violet follow the frequency bands.',config:{mode:'audio',audioMode:'spectrum',audioPalette:'aurora',sensitivity:1.3,brightness:120}},
  {id:'sunset-comet',name:'Sunset comet',tags:['music','warm'],description:'A warm comet with a broad fading tail.',config:{mode:'audio',audioMode:'comet',audioPalette:'sunset',audioSpeed:4,audioWidth:45,brightness:120}},
  {id:'ocean-energy',name:'Ocean energy',tags:['music','ocean'],description:'The blue palette fades with the whole mix.',config:{mode:'audio',audioMode:'energy',audioPalette:'ocean',sensitivity:1.2,brightness:105}},
  {id:'neon-duet',name:'Neon duet',tags:['music','gaming'],description:'Mirrored neon bands move together.',config:{mode:'audio',audioMode:'twin_bounce',audioPalette:'neon',audioSpeed:5,audioWidth:20,brightness:135}},
  {id:'forest-meters',name:'Forest meters',tags:['music','nature'],description:'Green volume bars grow from the center.',config:{mode:'audio',audioMode:'vu',audioPalette:'forest',sensitivity:1.3,brightness:115}},
  {id:'ember-ripple',name:'Ember ripples',tags:['music','warm'],description:'Narrow rings of orange and gold.',config:{mode:'audio',audioMode:'ripple',audioPalette:'ember',audioSpeed:4,audioWidth:15,brightness:115}},
  {id:'candy-beats',name:'Candy beats',tags:['music','pastel'],description:'Pink and blue expand with the audio level.',config:{mode:'audio',audioMode:'beat',audioPalette:'candy',sensitivity:1.4,brightness:120}},
  {id:'rainbow-bounce',name:'Rainbow bounce',tags:['music','rainbow'],description:'A wide rainbow band follows the sound.',config:{mode:'audio',audioMode:'bounce',audioPalette:'rainbow',audioSpeed:5,audioWidth:35,brightness:130}},
  {id:'custom-synth',name:'Synth blend',tags:['music','gaming'],description:'Purple and cyan blend through a moving ribbon.',config:{mode:'audio',audioMode:'wave',audioPalette:'custom',color:'#a85aff',audioSecondary:'#00dcda',audioSpeed:3,audioWidth:50,brightness:125}},
  {id:'selected-volume',name:'Warm volume',tags:['music','warm'],description:'The selected amber color responds through hardware brightness.',config:{mode:'audio',audioMode:'energy',audioPalette:'selected',color:'#efb575',sensitivity:1.4,brightness:120}},
  {id:'candy-comet',name:'Candy comet',tags:['music','pastel'],description:'A slim comet in pink, lavender and blue.',config:{mode:'audio',audioMode:'comet',audioPalette:'candy',audioSpeed:5,audioWidth:22,brightness:115}},
  {id:'aurora-wave',name:'Aurora ribbons',tags:['music','relax'],description:'Slow, wide ribbons in the aurora palette.',config:{mode:'audio',audioMode:'wave',audioPalette:'aurora',audioSpeed:2,audioWidth:55,brightness:100}},
  {id:'screen-esports',name:'Screen · Esports',tags:['gaming','fast'],description:'Minimal smoothing and compact capture for quick color changes.',config:{mode:'screen',fps:30,smoothing:0,depth:16,captureScale:.2,brightness:160}},
  {id:'screen-vivid',name:'Screen · Detailed',tags:['creative','detail'],description:'Full-size captures and wider edges for fine color detail.',config:{mode:'screen',fps:15,smoothing:25,depth:80,captureScale:1,brightness:155}},
  {id:'screen-reading',name:'Screen · Reading',tags:['focus','reading'],description:'Gentle, dim screen-following light for slower content.',config:{mode:'screen',fps:8,smoothing:80,depth:90,captureScale:.35,brightness:75}},
  {id:'screen-ultralight',name:'Screen · Quiet desktop',tags:['efficient','quiet'],description:'Five small captures per second with soft transitions.',config:{mode:'screen',fps:5,smoothing:60,depth:32,captureScale:.2,brightness:65}}
];
